os:
  - linux
  - osx
  - windows
sudo: false
language: go
go_import_path: m4o.io/pbf
env:
  global:
    - GO111MODULE=on
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
install:
  - GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go install github.com/mattn/goveralls
script:
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then $GOPATH/bin/golangci-lint run ; fi
  - $GOPATH/bin/goveralls -service=travis-ci -race -v
  - PBF_PROTO_BUFFER_SIZE=33554432 PBF_NCPU=4 go test -bench=. -benchtime=10s
after_success:
  - bash <(curl -s https://codecov.io/bash)
