os:
  - linux
  - osx
  - windows
sudo: false
language: go
go_import_path: m4o.io/pbf
# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.14 lands.
env:
  global:
    - GO111MODULE=on
    - GOLANGCILINT_VERSION=1.22.2
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip
install:
  - go get github.com/fzipp/gocyclo
  - curl -fsSL "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCILINT_VERSION}/golangci-lint-${GOLANGCILINT_VERSION}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}.tar.gz" | tar -xz --strip-components=1 -C "${TRAVIS_BUILD_DIR}/tmp-golangci-lint"
  - go install github.com/mattn/goveralls
script:
  - if [ "$TRAVIS_OS_NAME" != 'windows' ]; then $GOPATH/bin/gocyclo -over 15 $(go list -f {{.Dir}}/*.go ./...) ; fi
  - golangci-lint run
  - $GOPATH/bin/goveralls -service=travis-ci -race -v
  - PBF_PROTO_BUFFER_SIZE=33554432 PBF_NCPU=4 go test -bench=. -benchtime=10s
after_success:
  - bash <(curl -s https://codecov.io/bash)
